name: pridec

# NOTE: because forecsat relies on fetch, these should always be run via `docker compose run` to
# launch a specific service and not the whole workflow at once

services:
  fetch:
    build:
      context: ./fetch
      dockerfile: Dockerfile
    volumes:
     - type: bind
       source: ${HOST_PWD}/input
       target: /app/input
       bind:
          create_host_path: false
       read_only: false
    #specify new DISEASE_CODE env variable via ` docker compose run --env DISEASE_CODE=new_value --rm fetch`
    environment:
      DHIS2_PRIDEC_URL: "${DHIS2_PRIDEC_URL}"
      DHIS2_TOKEN: "${DHIS2_TOKEN}"
      PARENT_OU: "VtP4BdCeXIo"
      DISEASE_CODE: "${DISEASE_CODE}"

  forecast:
    build: 
      context: ./forecast
      dockerfile: Dockerfile
    volumes:
     - type: bind
       source: ${HOST_PWD}/input
       target: /app/input
       bind:
          create_host_path: false
       read_only: true
     - type: bind
       source: ${HOST_PWD}/output
       target: /app/output
       bind:
          create_host_path: false
       read_only: false
    #commands can be overridden when using docker compose run (not up)
    command: --config "input/config.json"

  post:
    build:
      context: ./post
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ${HOST_PWD}/output
        target: /app/output
        bind:
          create_host_path: false
        read_only: true
    environment:
      DHIS2_PRIDEC_URL: "${DHIS2_PRIDEC_URL}"
      DHIS2_TOKEN: "${DHIS2_TOKEN}"
      DISEASE_CODE: "${DISEASE_CODE}"
      DRYRUN: "true"
