name: pridec

# NOTE: these services are not meant to run in parellel. These should always be run via `docker compose run` to
# launch a specific service and not the whole workflow at once. Yes this could be updated using an API.

services:
  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    image: mvevans89/pridec_etl:0.1.1

  forecast:
    build: 
      context: ./forecast
      dockerfile: Dockerfile
    image: mvevans89/pridec_forecast:0.1.1


