name: pridec

# NOTE: because forecast relies on fetch, these should always be run via `docker compose run` to
# launch a specific service and not the whole workflow at once

# this compose file is used in the auto install that makes pridec app available anywhere
# should match compose.yaml in all ways except that volumes are relative to ${HOST_PWD}

services:

  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    #this is needed for testing using d2 instances on the localhost
    network_mode: "host"
    volumes:
     - type: bind
       source: ${HOST_PWD}/input
       target: /app/input
       bind:
          create_host_path: false
       read_only: false
     - type: bind
       source: ${HOST_PWD}/output
       target: /app/output
       bind:
          create_host_path: false
       read_only: false
     - type: bind
       source: ${HOST_PWD}/.gee-private-key.json
       target: /app/.gee-private-key.json
       bind:
          create_host_path: false
       read_only: true

  forecast:
    build: 
      context: ./forecast
      dockerfile: Dockerfile
    #this is needed for testing using d2 instances on the localhost
    network_mode: "host"
    cap_add:
      - SYS_NICE  
    volumes:
     - type: bind
       source: ${HOST_PWD}/input
       target: /app/input
       bind:
          create_host_path: false
       read_only: true
     - type: bind
       source: ${HOST_PWD}/output
       target: /app/output
       bind:
          create_host_path: false
       read_only: false