from typing import Protocol, runtime_checkable

@runtime_checkable
class RequestTrackerProtocol(Protocol):
    def save(self, log: dict) -> None: ...
    def get(self, request_id: str) -> dict | None: ...
    def list_recent(self, limit: int = 50, endpoint: str | None = None) -> list[dict]: ...